target_sources(
  obs-studio
  PRIVATE
    plugin-manager/PluginManager.cpp
    plugin-manager/PluginManager.hpp
    plugin-manager/PluginManagerWindow.cpp
    plugin-manager/PluginManagerWindow.hpp
    plugin-manager/PluginModuleLoader.hpp
)

if(OS_WINDOWS)
  target_sources(
    obs-studio
    PRIVATE
      plugin-manager/PluginModuleLoader-win.cpp
  )
elseif(OS_MACOS)
  target_sources(
    obs-studio
    PRIVATE
      plugin-manager/PluginModuleLoader-mac.mm
  )
else()
  target_sources(
    obs-studio
    PRIVATE
      plugin-manager/PluginModuleLoader-nix.cpp
  )
endif()
