target_sources(
  obs-studio
  PRIVATE
    plugin-manager/PluginManager.cpp
    plugin-manager/PluginManager.hpp
    plugin-manager/PluginManagerWindow.cpp
    plugin-manager/PluginManagerWindow.hpp
    $<$<PLATFORM_ID:Windows>:plugin-manager/PluginModuleLoader-win.cpp>
    plugin-manager/PluginModuleLoader.hpp
)
